FROM debian:bookworm

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        mosquitto \
        python3 \
        python3-pip && \
    apt clean

RUN python3 -m pip install pdm --break-system-packages

RUN mkdir -p /usr/local/src/dugway
WORKDIR /usr/local/src/dugway/

COPY README.md .
COPY pdm.lock .
COPY pyproject.toml .
COPY dugway .
RUN pdm install

RUN mkdir -p /app
WORKDIR /app
COPY self_tests/ .

CMD [ "/bin/bash" ]
