FROM debian:bookworm

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        curl \
        mosquitto \
        mosquitto-clients \
        python3 \
        python3-pip && \
    apt clean

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN mkdir -p /usr/local/src/dugway
WORKDIR /usr/local/src/dugway/

COPY README.md .
COPY uv.lock .
COPY pyproject.toml .
COPY src .
RUN uv sync
RUN uv build
RUN python3 -m pip install dist/dugway-0.1.0-py3-none-any.whl --break-system-packages

RUN mkdir -p /app
WORKDIR /app
COPY self_tests/ .

CMD [ "/bin/bash" ]
