version: "3"

tasks:
  default:
    deps:
      - format
      - test
      - lint

  format:
    desc: Format code with black
    cmds:
      - uv run black src tests

  lint:
    desc: Lint code with ruff
    cmds:
      - uv run ruff check src tests

  test:
    desc: Run the test suite with pytest
    cmds:
      - uv run pytest
